### ISSUE TITLE
OS Version detection doesn't work properly

### ISSUE THREAD

**Issue by rajbirs-cog** [GiovanniBussi/macports-ci#10]
In the case of OS version 10.xx.x, it works fine. It returns 10.xx.

But in the case of OS version 10.xx, it returns 10.

I faced this issue in macOS Catalina until I updated it to 10.15.1.

**Comment by GiovanniBussi** [comment]
Thanks for reporting!

How can I test Catalina on Travis? According to the [documentation](https://docs.travis-ci.com/user/reference/osx/#macos-version) it is not available yet.

Giovanni

**Comment by rajbirs-cog** [comment]
I have tested the changed command manually for 10.13.6 and 10.13.
It returns 10.13 for both cases.

Thank you, Giovanni.

I am closing the issue.
