### ISSUE TITLE
Cache installed ports in Travis CI

### ISSUE THREAD

**Issue by jiridanek** [GiovanniBussi/macports-ci#11]
I had a good experience zipping and restoring my entire MacPorts prefix into a /tmp subdirectory when working on a shared macOS computer. (I had a tight quota for my home dir, that is the reason for zipping. The computer's /tmp would be wiped every night.)

I believe that it should be possible to use Travis CI cache feature for the entire /opt/local subtreee and save time on repeatedly installing MacPorts, and the installing the same ports over and over again.

It would require logic to skip MacPorts install in case it is already present, and logic to uninstall unused old versions of ports, so they don't accumulate in the cache. The `sudo port uninstall inactive` might be a start.

Anybody experimented with Travis cache before? I tried the following, but it did not have any effect (binary packages were fetched over the network again, not reused from `/opt/local/var/macports/software`). Also, I'd like to cache the unpacked packages. Unpacking the entire cache at once should be faster than unpacking ports one by one.

```
    before_script:
    # configure local archive site
    - |
      sudo dd of=/opt/local/etc/macports/archive_sites.conf <<EOF
      name local
      urls file:///opt/local/var/macports/software
      EOF
    # install ports

    cache:
      directories:
        - /opt/local/var/macports/software
    before_cache:
      - sudo port uninstall inactive
```

edit: I took inspiration from https://trac.macports.org/wiki/howto/ShareArchives

**Comment by GiovanniBussi** [comment]
Did you try:
- caching the whole `/opt/local` tree just after having installed macports and the ports that you want to cache (making a single tar file)
- untar it just after having installed macports

If you preserve dates it should work. At the second round, ports that are already installed should not be installed again (unless they were updated upstream).

Concerning macports itself, I think caching is not sufficient since it also adds a new `macports` user (plus perhaps other stuff)

**Comment by jiridanek** [comment]
When I cache using Travis, the cache step (creating archive and uploading it out of VM) has to run as a last thing in the test job. I can delete files from disk right before, that I don't want cached. Cache restore has to run as one of the first steps in a test job, afaik right after some Travis init happens, and before any of customizable commands are run.

I guess I can delete the MacPorts install in the `before_cache` step, then cache the `/opt/local`. Thanks. Will try today or tomorrow.

**Comment by GiovanniBussi** [comment]
That's why I was proposing to use tar. Something like `tar czv $HOME/macports-cache.tgz /opt/local` so that you can decide at which point of the script you take the snapshot. It could be just after having installed the requirements of your package.

**Comment by jiridanek** [comment]
Aha. Right. Got It.
