### ISSUE TITLE
Support `source macports-ci` usage

### ISSUE THREAD

**Issue by Lingxi-Li** [GiovanniBussi/macports-ci#3]
If it is required to use MacPorts, maybe it should be done automatically in the script?

**Comment by GiovanniBussi** [comment]
Hi, as of now you launch the script in a separate shell, so it cannot change the environment of the calling shell. I should modify it so that it can be used also as
````
> source macports-ci
````

However, this would require some fix to the script

**Comment by Lingxi-Li** [comment]
I see. I'm not familiar with Linux, and thus not aware of this issue. Today I learned. Thanks for the quick reply 😄

**Comment by Lingxi-Li** [comment]
Yes, I think it would be much better to `source` rather than executing in an independent shell. Just compare the one-liner

~~~
source macports-ci
~~~

with

~~~
export COLUMNS=80
chmod +x ./macports-ci
./macports-ci install
~~~

Options are supported [the same](https://stackoverflow.com/a/39768838/1348273).

**Comment by Lingxi-Li** [comment]
This is a breaking change. Should add another version instead of modifying the existing one.
